バグ修正

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -30,8 +30,7 @@ jobs:
         pip install -r requirements.txt
 
     - name: Ensure browsers are installed
-      run: |
-        python -m playwright install --with-deps
+      run: python -m playwright install --with-deps
 
     - name: Install Testmo CLI tool locally (then use npx testmo .. to run it)
       run: npm install --no-save @testmo/testmo-cli
@@ -40,6 +39,10 @@ jobs:
       run: |
         mkdir -p test-results
         pytest --browser ${{ matrix.browser }} --junitxml=test-results/${{ matrix.os }}_${{ matrix.browser }}_results.xml --tracing=retain-on-failure 
+        if [ ! -f test-results/${{ matrix.os }}_${{ matrix.browser }}_results.xml ]; then
+          echo "Test results file not found!"
+          exit 1
+        fi
 
     - name: Upload test results
       uses: actions/upload-artifact@v4
